#!/bin/sh

for a in NR_LICENSE SLACK_WEBHOOK ROUTER_HOSTNAME ROUTER_USERNAME SNMPV3_USER SNMPV3_AUTH_PASS \
	SNMPV3_PRIV_PASS TUNNEL_USER TUNNEL_PASS TUNNEL_ID
do
	eval "tmp=\$$a"
	sed -i "s@%%$a%%@$tmp@" /config.yaml
done

echo "$ROUTER_SSH_PRIVKEY" > /id_ed25519
echo "$ROUTER_SSH_PUBKEY" > /known_hosts
